# Generated by Django 5.1.5 on 2025-02-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mylists.store",
            ),
        ),
    ]
