# Generated by Django 5.2 on 2025-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mylists", "0003_shoplist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoplist",
            name="items",
            field=models.ManyToManyField(blank=True, to="mylists.item"),
        ),
    ]
